### PR TITLE
[enhancement] add Pipeline FunctionList and use block-level scoping

### PR DESCRIPTION
**Pull request by DaveZLB**
Issue #152  @badboy-huaqiao

Signed-off-by: zhanglibin <zlibin@vmware.com>

### CODE REVIEW

**Comment by badboy-huaqiao** [comment]
@wshengqi please check it

**Comment by badboy-huaqiao** [comment]
@DaveZLB please add corresponding properties in edgexfoundry.js file
image

**Comment by DaveZLB** [comment]
> @DaveZLB please add corresponding properties in edgexfoundry.js file
> image



> @DaveZLB please add corresponding properties in edgexfoundry.js file
> image

done

**Comment by badboy-huaqiao** [comment]
@DaveZLB ok, @wshengqi because of @DaveZLB update your code function,  please check whether changed the original function of your code

**Comment by wshengqi** [comment]
@badboy-huaqiao huaqiao，I've seen it ，this pr has no problem, you can merge . Thank you

**Comment by badboy-huaqiao** [comment]
> @badboy-huaqiao huaqiao，I've seen it ，this pr has no problem, you can merge . Thank you

okay

**Pull request merged**
