### PR TITLE
feat: update go-mod-bootstrap dep

### PR DESCRIPTION
**Pull request by dovholuknf**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [ ] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)

### CODE REVIEW

**Review by cloudxxx8 — CHANGES_REQUESTED** [review]
please also push the go.sum

**Comment by dovholuknf** [comment]
i can't explain it, but even after I run go mod tidy, the go sum file doesn't change. i even deleted go.sum, then regenerated it with go mod tidy and the file is the same.

**Comment by cloudxxx8** [comment]
I ecnountered the same issue, but it works after I manually upgrade other direct modules
Please review my PR here
https://github.com/edgexfoundry/edgex-ui-go/pull/772

**Comment by dovholuknf** [comment]
Thanks. I'll close this pr. The UI isn't vital, but might as well keep it up to date

**Comment by cloudxxx8** [comment]
I just realized the problem is from this line
https://github.com/edgexfoundry/edgex-ui-go/blob/a8d6b1442bc468e13692d3d2eaadfc8c4e6675cc/go.mod#L140

**Comment by dovholuknf** [comment]
hahaha oooops. how'd that sneak in and get through the review process? :) I pushed the change if you want to keep my pr (or yours, whichever)

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Pull request merged**
