### PR TITLE
feat: Add Provision Watchers tab to Metadata 

### PR DESCRIPTION
**Pull request by A808597949**
show provision watcher list
add a new provision watcher
edit a provision watcher
delete a provision watcher

If your build fails due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-ui-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [x] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [x] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

### CODE REVIEW

**Comment by cloudxxx8** [comment]
@A808597949 @Ambition-J 
Could anyone of your team member help review the PR?  We don't have Angular expertise to review this.
There is another PR with the same name.  Is there any duplication?
https://github.com/edgexfoundry/edgex-ui-go/pull/625

@jumpingliu for awareness

**Comment by A808597949** [comment]
The submission at #625 does not meet the standard, so I have resubmitted it.

**Review by Ambition-J — APPROVED** [review]

**Comment by cloudxxx8** [comment]
recheck

**Comment by cloudxxx8** [comment]
@A808597949 the `make test` fails, so the validation cannot be passed
please adjust the code to make sure `make test` can be passed

**Comment by A808597949** [comment]
@cloudxxx8 I have adjusted the code, and now 'make test' passes successfully.

**Comment by cloudxxx8** [comment]
The Jenkins automation validation is still failed.  Do you have any ideas about the following error?
@ernestojeda is there anything to do from DevOps for the npm upgrade?

> [2023-09-04T02:39:07.381Z] npm ERR! code EBADENGINE
> [2023-09-04T02:39:07.381Z] npm ERR! engine Unsupported engine
> [2023-09-04T02:39:07.381Z] npm ERR! engine Not compatible with your version of node/npm: npm@10.0.0
> [2023-09-04T02:39:07.381Z] npm ERR! notsup Not compatible with your version of node/npm: npm@10.0.0
> [2023-09-04T02:39:07.381Z] npm ERR! notsup Required: {"node":"^18.17.0 || >=20.5.0"}
> [2023-09-04T02:39:07.381Z] npm ERR! notsup Actual:   {"npm":"8.15.0","node":"v16.17.1"}
> [2023-09-04T02:39:07.381Z] 
> [2023-09-04T02:39:07.381Z] npm ERR! A complete log of this run can be found in:
> [2023-09-04T02:39:07.381Z] npm ERR!     /root/.npm/_logs/2023-09-04T02_39_06_760Z-debug-0.log
> [2023-09-04T02:39:07.381Z] The command '/bin/sh -c npm install -g npm' returned a non-zero code: 1
> [2023-09-04T02:39:07.381Z] make[1]: *** [Makefile:82: edgex-web-ui.imagebuilt] Error 1

https://jenkins.edgexfoundry.org/blue/organizations/jenkins/edgexfoundry%2Fedgex-ui-go/detail/PR-630/3/pipeline/

**Comment by ernestojeda** [comment]
@cloudxxx8 I think all that needs to be done is change this line: https://github.com/edgexfoundry/edgex-ui-go/blob/main/web/Dockerfile#L1 to a newer version of NodeJS. 18 or 20 should work: https://hub.docker.com/_/node

**Comment by cloudxxx8** [comment]
@A808597949 could you please make the change based on @ernestojeda 's suggestion?

**Comment by A808597949** [comment]
I tried changing the version of Node.js, but I encountered errors when running 'make test' locally. I'm currently looking for a solution.

**Comment by cloudxxx8** [comment]
@A808597949 do you have any progress for this PR?
this is blocking https://github.com/edgexfoundry/edgex-ui-go/pull/632

**Comment by A808597949** [comment]
I will try it

**Comment by cloudxxx8** [comment]
please help rebase first

**Review by cloudxxx8 — APPROVED** [review]
approve based on @Ambition-J 's review

**Comment by lenny-intel** [comment]
@A808597949 please see https://github.com/edgexfoundry/edgex-ui-go/issues/642

**Pull request merged**
