### PR TITLE
fix: Adaptation to V3 true/false for ds-pushevent ds-returnevent

### PR DESCRIPTION
**Pull request by mglmc**
All the yes/no related to ds-returnevent and ds-pushevents has been replaced

Close: #626

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [x] I have added unit tests for the new feature or bug fix (if not, why?)
-- No new UT are needed
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
-- The WEB has been deploy locally and the make test has been done.
- [x] I have opened a PR for the related docs change (if not, why?)
-- Not needed

## Testing Instructions

Running the web as the official doc said.

### CODE REVIEW

**Comment by mglmc** [comment]
Sign-off added

I saw that the issue #626 was opened and here it is the solution.

Additionally, later I saw that there was a PR (https://github.com/edgexfoundry/edgex-ui-go/pull/595) opened from April, however it is still stuck.

As suggestion, I saw that there is a folder with the transpilation of the WEB. Maybe, is it a good idea to create/modify the .gitignore to ignore that folder and remove all the files that are generated?

**Comment by A808597949** [comment]
I am an official representative, and I will be following up on this issue. I apologize for the delayed response and sincerely appreciate your contribution and suggestions.

**Comment by mglmc** [comment]
> @mglmc, I am unable to review the package-lock.json file due to large amount of changes. I suspect that these are un-related white space changes. Please undo all these unrelated white space changes.

@lenny-intel uploaded without the package-lock file

**Review by lenny-intel — APPROVED** [review]
LGTM

**Pull request merged**
