### PR TITLE
fix: Unauthorized API in profile yaml

### PR DESCRIPTION
**Pull request by jiekechoo**
Closes: #624

If your build fails due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-ui-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [ ] I am not introducing a new dependency (add notes below if you are)
- [x] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

### CODE REVIEW

**Comment by lenny-intel** [comment]
@jiekechoo , I just verified latest UI is working fine in secure mode after https://github.com/edgexfoundry/edgex-ui-go/pull/645 merged. Please make sure you have latestest napa dev image by running `make pull` from compose builder.

If you are still having an issue, please create new issue describing it in detail, rather that referencing and unrelated closed issue.

**Comment by jiekechoo** [comment]
> @jiekechoo , I just verified latest UI is working fine in secure mode after #645 merged. Please make sure you have latestest napa dev image by running `make pull` from compose builder.
> 
> If you are still having an issue, please create new issue describing it in detail, rather that referencing and unrelated closed issue.

@lenny-intel Yes, I use the commit ` e15caff7a7271d7299d27016bfbe034a7a0b899b` from edgex-go after #645. I'll pull the latest commit to use 'make docker' command test again.

**Comment by jiekechoo** [comment]
@lenny-intel This is my local commit log, I'm sure it is after #645 .

image

the code L41 need to get `jwtSecretProvider`: 
https://github.com/edgexfoundry/edgex-ui-go/blob/27d7f0953c9fdd47967e32fc16da1d0dd0b862e0/internal/handler/profile.go#L41 

so, it should be set `true` in bootstrap.Run, L66:
https://github.com/edgexfoundry/edgex-ui-go/blob/27d7f0953c9fdd47967e32fc16da1d0dd0b862e0/internal/service/service.go#L56-L73

**Comment by lenny-intel** [comment]
@jiekechoo , the UI doesn't run in secure mode like the other services. See my comment here: https://github.com/edgexfoundry/edgex-compose/pull/419#issuecomment-1796121404

**Comment by jiekechoo** [comment]
If you don't set `SecretProvider` as `true` in UI bootstrap.Run when Secure Mode is enabled, it desn't work. 
Even set `SecretProvider` as `true` in no-secty mode, it desn't matter.

**Comment by jiekechoo** [comment]
@lenny-intel 
I tried again with latest commit of edgex-compose 
image

and the images and containers show blow:
image

but, when I access web UI,  error 401:
image

**Comment by lenny-intel** [comment]
> If you don't set `SecretProvider` as `true` in UI bootstrap.Run when Secure Mode is enabled, it desn't work.

We have never set it. This would give the UI access without the user having to login with the token.
Loading profile list works fine, loading, editing Devices works fine. 
So there is something else wrong.
@bnevis-i we need your help debugging [this issue](https://github.com/edgexfoundry/edgex-ui-go/issues/631).

**Pull request closed without merging**
