### PR TITLE
feat: add custom grafana datasource plugin for edgexfoundry

### PR DESCRIPTION
**Pull request by badboy-huaqiao**
Signed-off-by: Huaqiao Zhang <huaqiaoz@vmware.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-ui-go/blob/master/.github/Contributing.md.

## What is the current behavior?

Add custom grafana datasource plugin for edgexfoundry

## What is the new behavior?
Add custom grafana datasource plugin for edgexfoundry

## Does this PR introduce a breaking change?

- [ ] Yes
- [* ] No

## New Imports

- [ ] Yes
- [* ] No

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

### CODE REVIEW

**Review by thank037 — APPROVED** [review]

**Review by thank037 — CHANGES_REQUESTED** [review]
LGTM

**Comment by badboy-huaqiao** [comment]
> it doesn't seem to me have the permission

that's ok. thanks.

Hi @bnevis-i , who has the permission to review it? do you have?

**Comment by badboy-huaqiao** [comment]
> > it doesn't seem to me have the permission
> 
> that's ok. thanks.
> 
> Hi @bnevis-i , who has the permission to review it? do you have?

cc @jpwhitemn

**Comment by bnevis-i** [comment]
According to Github, only @badboy-huaqiao and @lenny-intel are committers to this repo.  ("Houston, we have a problem" [misquoted])

https://github.com/orgs/edgexfoundry/teams?query=edgex-ui-go

**Comment by badboy-huaqiao** [comment]
> According to Github, only @badboy-huaqiao and @lenny-intel are committers to this repo. ("Houston, we have a problem" [misquoted])
> 
> https://github.com/orgs/edgexfoundry/teams?query=edgex-ui-go

geat thanks @bnevis-i , and @lenny-intel please review this PR

**Comment by badboy-huaqiao** [comment]
Hi @bnevis-i, I want to know if @lenny-intel is still working on this repository? if not, could you review it? this PR is an example about edgex intergrating with grafana.

**Comment by bnevis-i** [comment]
@badboy-huaqiao I am willing to review it but need detailed instructions on how to test it.

**Comment by badboy-huaqiao** [comment]
@bnevis-i it's diffcult to test online right now, it needs a grafana instance running, and then it needs to build using command `yarn dev` or `yarn build`, and then move the built artifact under a folder which granfana can find, and i have made a video showing how to do that, Gavin has uploaded it to Chinese community, he will upload it to youtube later. here, we just want to let user can download this integrated code, If you think this is not appropriate, is there another suitable place to store it？

**Comment by bnevis-i** [comment]
How about if we can get an independent developer to attest they've gone through the above process and verified it works?  I could approve based on that.

**Comment by badboy-huaqiao** [comment]
> How about if we can get an independent developer to attest they've gone through the above process and verified it works? I could approve based on that.

That's good, you can find a developer you know to test it.
Anther question, I found @thank037 who's working on GUI with me before had been removed from edgex-ui-commiters team which is the reason he didn't have the review permission any more , so is this the behavior of system or the repository managers?

**Pull request closed without merging**
