### PR TITLE
feat: Update README.md

### PR DESCRIPTION
**Pull request by nil4git**
correct command : make docker run_docker

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-ui-go/blob/master/.github/Contributing.md.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## New Imports

- [ ] Yes
- [x] No

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

### CODE REVIEW

**Comment by nil4git** [comment]
rectifying the make docker run_docker command 
make run_docker doesnt work

**Review by badboy-huaqiao — APPROVED** [review]
@nil4git please add signed-off-by tag for each commit, so I can approve your PR

**Comment by nil4git** [comment]
I have done adding onto signed-off details using below set of command
git commit --amend --no-edit --signoff
git push origin HEAD:master

Kindly cross check & Thanks

**Comment by nil4git** [comment]
> @nil4git please add signed-off-by tag for each commit, so I can approve your PR

I have done adding onto signed-off details using below set of command
git commit --amend --no-edit --signoff
git push origin HEAD:master

Kindly cross check & Thanks

**Comment by badboy-huaqiao** [comment]
@nil4git we can see the status of DCO above is not passed and it is a required features which will block this PR

**Comment by nil4git** [comment]
> @nil4git we can see the status of DCO above is not passed and it is a required features which will block this PR

I have made a pull request with this commit id: https://github.com/nil4git/edgex-ui-go.git
This has the sign off tag as well 
kindly review and thanks

**Comment by badboy-huaqiao** [comment]
this PR is invalid because DCO is not passed, move to PR #411

**Pull request closed without merging**
