### PR TITLE
Update add-device.component.ts

### PR DESCRIPTION
**Pull request by blucruz**
Fix a bug concerned with MQTT CommandTopic (previously Topic). This would cause error log: 'app=$device_name source=executor.go:54 msg="AutoEvent - error occurs when reading resource message: error reading DeviceResourece message for $device_name -> 'CommandTopic' not found in the 'mqtt' protocol properties"'

## PR Checklist
Please check if your PR fulfills the following requirements:

- [. ] Tests for the changes have been added (for bug fixes / features)
- [. ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-ui-go/blob/master/.github/Contributing.md.

## What is the current behavior?

When you add a MQTT device, the device service would cause error log: 'app=$device_name source=executor.go:54 msg="AutoEvent - error occurs when reading resource message: error reading DeviceResourece message for $device_name -> 'CommandTopic' not found in the 'mqtt' protocol properties"'

## Does this PR introduce a breaking change?

- [ ] Yes
- [. ] No

## New Imports

- [ ] Yes
- [ .] No

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

### CODE REVIEW

**Comment by badboy-huaqiao** [comment]
@blucruz ？

**Comment by blucruz** [comment]
> @blucruz ？

I wanted to make some bugfix, but CI-robot said my commit was not of compliance.

**Comment by badboy-huaqiao** [comment]
@blucruz don't forget to add signed-off for your git config, and each one commit message should follow the `git commit` instructions, such as , feat, fix, refactor.  For more information, please refer to the git signed-off and git commit manuals.

**Comment by badboy-huaqiao** [comment]
hi @blucruz I think you have made a good catch! if you feel inconvenient to submit a PR, you can creat an associated issue addressing this matter, thanks.

**Pull request closed without merging**
