### PR TITLE
fix: Dashboard and Metadata device count.

### PR DESCRIPTION
**Pull request by jiekechoo**
If your build fails due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-ui-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [x] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [x] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

always `20`:
image
fix to:
image

always `20`:
image
fix to:
image

### CODE REVIEW

**Comment by badboy-huaqiao** [comment]
@jiekechoo good job, please refer [here](https://github.com/edgexfoundry/edgex-ui-go/blob/main/.github/Contributing.md) and include `Signed-off-by: Author Name <authoremail@example.com>` in every commit message, that will help your PR pass

**Comment by cloudxxx8** [comment]
@jiekechoo please help rebase the PR and follow the DCO convention as @badboy-huaqiao mentioned

**Comment by cloudxxx8** [comment]
@jiekechoo please rebase and squash your commit with -s or --sign-off
Here is the DCO failed message:
`To avoid having PRs blocked in the future, always include Signed-off-by: Author Name <authoremail@example.com> in every commit message. You can also do this automatically by using the -s flag (i.e., git commit -s).`

Also, for the Semantic PR check, you need to add a `:` after fix, for example `fix: Correct the device count on dashboard`
Not only PR name, but also commit message.

**Comment by jiekechoo** [comment]
I'll fix the bug in a new PR before Nov 10th. So close.

**Comment by lenny-intel** [comment]
@jiekechoo please see https://github.com/edgexfoundry/edgex-ui-go/pull/643

Need help debugging why no content is displayed. Thanks!

**Pull request closed without merging**
