### PR TITLE
feat: add security response header and cache control header and remove Authorization request header under insecure mode 

### PR DESCRIPTION
**Pull request by badboy-huaqiao**
close issue #462 
- add security response headers 
- add cache control response headers
- remove `Authorization` request header under insecure mode

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [ ] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [ ] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

### CODE REVIEW

**Comment by badboy-huaqiao** [comment]
@bnevis-i Hi, I have just updated the relevant issue, except for `Content-Security-Policy` feature, I did't figure out what value should be set, I try the values like `default-src 'self';` or `default-src 'self'; style-src 'self' 'unsafe-inline';` which provided by angular document, but it will cause the css and js file invalid. do you have any better advice?

**Review by bnevis-i — DISMISSED** [review]
Have you tried https://chrome.google.com/webstore/detail/csp-content-security-poli/fmkkdpolbaacmofciknnofgkknjpbhpm to help in generating the CSP?

**Comment by badboy-huaqiao** [comment]
> Have you tried https://chrome.google.com/webstore/detail/csp-content-security-poli/fmkkdpolbaacmofciknnofgkknjpbhpm to help in generating the CSP?

@bnevis-i great thanks for your effort works, the tools you provided looks like not working on localhost, I did't find the  reason, but  i used the similar tools like https://csp-evaluator.appspot.com/ which told me No CSP headers found for this domain! Although I have set the CSP response header.

but at your suggestion, I went deeper research and set a set of values of CSP, it works now!

Apparently, it still needs to do more deeper research on CSP, you know security is a very deep area, I'm not familiar with the direction of security, you also saw that our GUI backend server is not a professional web service, it just used a FileServer provided by golang builtin package. 

I will create a new issue for further deeper research and update on this aspect.

please review it again and we can close it now.
great thanks for your works again.

**Review by bnevis-i — APPROVED** [review]

**Comment by bnevis-i** [comment]
> but at your suggestion, I went deeper research and set a set of values of CSP, it works now!

The browser places pretty much no limits on GET requests, leading to the development of what were called "mashups" (https://en.wikipedia.org/wiki/Mashup_(web_application_hybrid) which load stuff from a lot of places and put it on a single web page.  But that same capability can be used by attackers to get your web browser to load content from places you haven't vetted and don't control.  CSP is all about placing constraints on what domains are part of your application, and excluding everything else, thereby deterring an attacker from creating a mashup that contains malicious content.


> Apparently, it still needs to do more deeper research on CSP, you know security is a very deep area, I'm not familiar with the direction of security, you also saw that our GUI backend server is not a professional web service, it just used a FileServer provided by golang builtin package.

It's probably good enough.  One doesn't need a powerful web server for angular based apps, as most of the processing is done client side, and I think as for as scale you only need to support one or two users, right?

**Comment by badboy-huaqiao** [comment]
@bnevis-i good job,you are right, for now the scope of GUI is enough, we maybe just properly enhance the GUI backend server we have now，more deeper discussion move to isssue #509 , thanks for your works.

**Pull request merged**
