### PR TITLE
remove snap dir

### PR DESCRIPTION
**Pull request by ernestojeda**
Remove snap support based on conversation with @tonyespy and @jamesrgregg  in the DevOps WG meeting 04/16/2020

### CODE REVIEW

**Comment by jamesrgregg** [comment]
@tonyespy 
my meeting minutes from yesterday on this are a little weak.  
edgex-ui-go << Geneva Snap??
Per Tony –was never released to stable channel (beta hasn’t been updated)
Suggestion to include in main edgex
I'm assuming this is a suggestion to include edgex-ui-go in the main snap edgex channel with all the others??

**Comment by ernestojeda** [comment]
> @tonyespy
> my meeting minutes from yesterday on this are a little weak.
> edgex-ui-go << Geneva Snap??
> Per Tony –was never released to stable channel (beta hasn’t been updated)
> Suggestion to include in main edgex
> I'm assuming this is a suggestion to include edgex-ui-go in the main snap edgex channel with all the others??

Right. It is going to be incorporated into the edge-go snap itself.

**Comment by badboy-huaqiao** [comment]
@ernestojeda @jamesrgregg @tonyespy Hi all, have you reached an agreement? I see this PR open all the time.

**Comment by jamesrgregg** [comment]
> LGTM

this was my approval but I realized I was logged in with a different account

**Pull request merged**
